pmu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import (dashboard,user_information)
from views.user_information import (UserInformationStorage,saveimage)
from views.login import (signin,signout,homepage,login_popup,intermidate_login,PMULoginAPI )
from views.homepage import (feedback,email_validation)
from projectmanagement.manage_roles import (projectuserslist,projectuseradd,
                                            projectuseredit)
from budgetmanagement.manage_budget import (projectbudgetadd,projectbudgetlist,
                                            projectbudgetcategoryadd,projectlineitemadd,
                                            projectbudgetdetail,budgetutilization,
                                            budgetview,year_quarter_list,
                                            budgetlineitemedit,month_quarter_list,
                                            category_listing,category_add,
                                            delete_category,category_name_validate)
from userprofile.views import *
import userprofile
from django.conf.urls import handler404, handler500
import private_storage.urls
from media.views import PrivateStorageDownloadView
handler404 = userprofile.views.handler404
handler500 = userprofile.views.handler500

admin.autodiscover()

roles_patterns = ([
    url(r'^project/role/list/$',projectuserslist),
    url(r'^project/role/add/$',projectuseradd),
    url(r'^project/role/edit/$',projectuseredit),
    url(r'^project/budget/list/$',projectbudgetlist),
    url(r'^project/budget/create/$',projectbudgetadd),
    url(r'^project/budget/category/add/$',projectbudgetcategoryadd),
    url(r'^project/budget/lineitem/add/$',projectlineitemadd),
    url(r'^project/budget/detail/$',projectbudgetdetail),
    url(r'^project/budget/report-utilization/$',budgetutilization),
    url(r'^project/budget/view/$',budgetview),
    url(r'^quarter/list/$',year_quarter_list),
    url(r'^month/list/$',month_quarter_list),
    url(r'^project/budget/lineitem/edit/$',budgetlineitemedit),
    url(r'^project/budget/category/listing/$',category_listing),
    url(r'^project/budget/add/category/$',category_add),
    url(r'^project/budget/category/delete/$',delete_category),
    url(r'project/category/exists/$',category_name_validate),

])

userroles_patterns = ([

    url(r'^list/(?P<model>(:?user|role|menu))/$', UserListView.as_view()),
    url(r'^list/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserListView.as_view()),
    url(r'^add/(?P<model>(:?role|user|menu))/$', UserAddView.as_view()),
    url(r'^add/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserAddView.as_view()),
    url(r'^edit/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserEditView.as_view()),
    url(r'^edit/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserEditView.as_view()),
    url(r'^active/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserActive.as_view()),
    url(r'^active/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserActive.as_view()),
    url(r'^manage/role/(?P<pk>\d+)/$', manage_role),
    url(r'^manage/menu/(?P<pk>\d+)/$', manage_menu),
    url(r'^manage/active/(?P<pk>\d+)/$', object_active),
])


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^dashboard/$',dashboard.admin_dashboard),
    url(r'^project/',include('projectmanagement.urls')),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^upload/',include('media.urls')),
    url(r'^report/',include('budgetmanagement.report_urls')),
    url(r'^login/$',signin),
    url(r'^$',homepage),
    url(r'^login-popup/$',login_popup),
    url(r'^feedback/$',feedback),
    url(r'^email-valid/$',email_validation),
    url(r'^managing/',include('taskmanagement.urls')),
    url(r'^manage/user-access/$',UserInformationStorage.as_view()),
    url(r'^logout/$',signout),
    url(r'^save/image/$',saveimage),
    url(r'^manage/', include(roles_patterns)),
    url(r'^usermanagement/',include(userroles_patterns)),
    url(r'^intermidate-login/', intermidate_login),
    url(r'^pmu/login/$',PMULoginAPI.as_view()),
    url(r'^private-media/$', include(private_storage.urls)),
    url(r'^private-media/(?P<path>.*)$',PrivateStorageDownloadView.as_view(),  name='serve_private_file'),
]

taskmanagement/models.py
from django.db import models
from django.utils.encoding import smart_str, smart_unicode
from projectmanagement.manager import ActiveQuerySet
from django.template.defaultfilters import slugify
from constants import  OPTIONAL
import six
from django.contrib import admin
from django.views import generic
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from simple_history.models import HistoricalRecords
from thumbs import ImageWithThumbsField
from simple_history.admin import SimpleHistoryAdmin
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from projectmanagement.models import BaseContent

#----------------------introduction------------------------------------------#
# Task Management is the application where database tables are related to Activity,Task,Milestone
#--------------------ends here--------------------------------------------------#

ACTIVITY_CHOICES = ((1,'Core'),(2,'Non-core'),)
STATUS_CHOICES = ((0,' '),(1, 'Open'), (2, 'Close'), (3, 'Ongoing'),)

# Activity model
class Activity(BaseContent):
    project = models.ForeignKey("projectmanagement.Project",**OPTIONAL)
    super_category = models.ForeignKey("budgetmanagement.SuperCategory",**OPTIONAL)
    name = models.CharField(max_length=600,**OPTIONAL)
    activity_type = models.IntegerField(choices = ACTIVITY_CHOICES,default=1)
    status = models.IntegerField( choices = STATUS_CHOICES,default=0)
    description = models.TextField(**OPTIONAL)
    created_by = models.ForeignKey("projectmanagement.UserProfile",related_name ='activity_created_user',blank=True,null=True)
    assigned_to = models.ForeignKey("projectmanagement.UserProfile",related_name ='activity_asigned_user',blank=True,null=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'activity_subscriber_user',blank=True )
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s",**OPTIONAL)
    object_id = models.IntegerField(_('object ID'),**OPTIONAL)
    relatedTo = GenericForeignKey(ct_field="content_type", fk_field="object_id")
    history = HistoricalRecords()
    
    def __str__(self):
        return str(self.name)
    def __unicode__(self):
        return unicode(self.name)

# task model
class Task(BaseContent):
    name = models.CharField(max_length=600,**OPTIONAL)
    activity = models.ForeignKey(Activity)
    start_date=models.DateTimeField(**OPTIONAL)
    end_date=models.DateTimeField(**OPTIONAL)
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    actual_start_date = models.DateTimeField(**OPTIONAL)
    actual_end_date = models.DateTimeField(**OPTIONAL)
    status = models.IntegerField(choices = STATUS_CHOICES,default=0)
    task_dependency = models.ManyToManyField('self',blank=True,symmetrical=False)
    created_by = models.ForeignKey("projectmanagement.UserProfile",related_name ='task_created_user',**OPTIONAL)
    assigned_to = models.ForeignKey("projectmanagement.UserProfile",related_name ='task_assigned_user',blank=True,null=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'task_subscriber_user',blank=True )
    task_progress = models.CharField(max_length=100,**OPTIONAL)
    history = HistoricalRecords()

    def __str__(self):
        return smart_str(self.name) or ''
    def __unicode__(self):
        return unicode(self.name)

    def is_dependent(self):
        task = Task.objects.filter(task_dependency = self.id)
        if task:
            return True
        else :
            return False
    
    def task_attachments(self):
        inner_attach=[]
        from datetime import datetime
        from media.models import Attachment,Comment
        comment = Comment.objects.filter(active=2,content_type=ContentType.objects.get(model=('task')),object_id=self.id).order_by('-id')
        comment_dates = list(set([i.date() for i in comment.values_list('created',flat=True)]))
        task_progress_history = self.history.filter(task_progress__isnull=False).order_by('-id')
        attachments = Attachment.objects.filter(active=2,content_type=ContentType.objects.get(model=('task')),object_id=self.id).order_by('-id')
        attach_dates = list(set([i.date() for i in attachments.values_list('modified',flat=True)]))
        task_progress_dates = list(set([i.date() for i in task_progress_history.values_list('modified',flat=True)]))
        
        distinct_dates = attach_dates + comment_dates + task_progress_dates
        
        attach = []
        if distinct_dates:
            for date in list(set(distinct_dates)):
                inner_attach =[]
                for i in attachments.filter(created__range = (datetime.combine(date, datetime.min.time()),datetime.combine(date, datetime.max.time()))):
                    inner_attach.append(i)
                attach.append({date:inner_attach})
            attach = sorted(attach, key=lambda key: key,reverse=True)
        else:
            attach=[]
        return attach

# milestone model
class Milestone(BaseContent):
    project = models.ForeignKey("projectmanagement.Project",**OPTIONAL)
    name = models.CharField(max_length=300,**OPTIONAL)
    task = models.ManyToManyField(Task,blank=True)
    overdue = models.DateTimeField(**OPTIONAL)
    status = models.IntegerField(choices = STATUS_CHOICES,default=0)
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'milestone_subscriber_user',blank=True )
    history = HistoricalRecords()
    def __str__(self):
        return smart_str(self.name)
    def __unicode__(self):
        return unicode(self.name)

# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.


# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
 # When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
 # When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.

templates/listing.html
{% extends 'base.html' %}

{% block content %}
<!--Green pad Ends-->
<!--Content part starts-->
<section class="content-part">
	<div class="row">
	<div class="content-top">
	<div class = "header">
	    {% if model_name == 'Activity' %}
    <h3 class="box-title">Activity List</h3>
    {% endif %}
    {% if model_name == 'Task' %}
    <h3 class="box-title">Task List</h3>
    {% endif %}
    {% if model_name == 'Milestone' %}
    <h3 class="box-title">Milestone List</h3>
    {% endif %}
	</div>
<!--      <div class="select-area search_area">-->
<!--      	<label>Search</label>-->
<!--   -->
<!--		<input id="activate_tagator2" type="text" class="tagator" placeholder="Name or Type" data-tagator-show-all-options-on-focus="true" data-tagator-autocomplete="['Budget', 'Report', 'Document', 'Files', 'Budget', 'Report', 'Document', 'Task', 'Worksheet']">-->
<!--        <img src="/static/img/search-icon.png">-->
<!--         </div>-->
    </div>
    <div class="white-box white-pad">
    <div class="table-responsive">
    	<table class="table table-striped table-bordered sort_table" id="dest">
  <thead>
    {% if model_name == 'Activity' %}
            <tr>
                <th>Activity Name</th>
                <th>Super category</th>
                <th>Activity type</th>
                <th>Status</th>
                <th>Description</th>
                <th>Update</th>
                <th>Action</th>
            </tr>
            {% endif %}
            
            {% if model_name == 'Task' %}
            <tr>
                <th>Task Name</th>
                <th>Activity</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Status</th>
                <th>Update</th>
                <th>Action</th>
            </tr>
            {% endif %}
            
            {% if model_name == 'Milestone' %}
            <tr>
                <th>Milestone Name</th>
                <th>Task</th>
                <th>Over due date</th>
                <th>Update</th>
                <th>Action</th>
            </tr>
            {% endif %}
            
        </thead>
  </thead>
  <tbody>
    {% if model_name == 'Activity'%}
<!--            <div align = "right">-->
<!--                <a class="btn btn-primary" href="/manage/Activity/ActivityForm/add/"><i class="fa fa-edit"></i> Add</button>  </a>-->
<!--            </div>-->
        {% for i in obj_list %}
        <tr>
            <td>{{i.name}}</a></td>
            <td>{{i.super_category}}</td>
            <td>{{i.get_activity_type_display}}</td>
            <td>{{i.get_status_display}}</td>
            <td>{{i.description|safe}}</td>
            <td><a class="btn btn-primary" href="/managing/Activity/ActivityForm/edit/{{i.slug}}"><i class="fa fa-edit"></i> Edit</button> </a></td>
            {% ifequal i.active 2 %}
            <td><a class="btn btn-primary" href="/managing/activity/status/?id={{i.id}}&status=2" onclick="return deactivate()">Deactivate</button></a></td>
            {% else %}
            <td><a class="btn btn-success" href="/managing/activity/status/?id={{i.id}}&status=3" onclick="return activate()">Activate</button></a></td>
            {% endifequal %}
        </tr>
        {% endfor %}
        {% endif %}
        
        {% if model_name == 'Task'%}
            <div align = "right">
                <a class="btn btn-primary" href="/managing/Task/TaskForm/add/"><i class="fa fa-edit"></i> Add</button>  </a>
            </div>
        {% for i in obj_list %}
        <tr>
            <td>{{i.name}}</a></td>
            <td>{{i.activity}}</td>
            <td>{{i.start_date}}</td>
            <td>{{i.end_date}}</td>
            <td>{{i.get_status_display}}</td>
            <td><a class="btn btn-primary" href="/managing/Task/TaskForm/edit/{{i.slug}}"><i class="fa fa-edit"></i> Edit</button>  </a></td>
            {% ifequal i.active 2 %}
            <td><a class="btn btn-primary" href="/managing/task/status/?id={{i.id}}&status=2" onclick="return deactivate()">Deactivate</button></a></td>
            {% else %}
            <td><a class="btn btn-success" href="/managing/task/status/?id={{i.id}}&status=3" onclick="return activate()">Activate</button></a></td>
            {% endifequal %}
        </tr>
        {% endfor %}
        {% endif %}
        
        {% if model_name == 'Milestone'%}
            <div align = "right">
                <a class="btn btn-primary" href="/managing/Milestone/MilestoneForm/add/"><i class="fa fa-edit"></i> Add</button>  </a>
            </div>
        {% for i in obj_list %}
        <tr>
            <td>{{i.name}}</a></td>
            <td>{% for tasks in i.task.all %}<br>{{forloop.counter}}. {{tasks}}</br>{% endfor %}</td>
            <td>{{i.overdue}}</td>
            <td><a class="btn btn-primary" href="/managing/Milestone/MilestoneForm/edit/{{i.id}}"><i class="fa fa-edit"></i> Edit</button>  </a></td>
            {% ifequal i.active 2 %}
            <td><a class="btn btn-default" href="/managing/milestone/status/?id={{i.id}}&status=2" onclick="return deactivate()">Deactivate</button></a></td>
            {% else %}
            <td><a class="btn btn-success" href="/managing/milestone/status/?id={{i.id}}&status=3" onclick="return activate()">Activate</button></a></td>
            {% endifequal %}
        </tr>
        {% endfor %}
        {% endif %}
  </tbody>
</table>
        </div>
          <div class="pagination_no">
        <div id="pagination-long"></div>
    </div>
    </div>
    
    
    
    </div>
</section>
<!--Content part Ends-->
{% endblock %}



templates/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Login | GoodCSR-PMU Admin</title>
  <link rel="shortcut icon" href="/static/img/favicon.ico">
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/static/plugins/iCheck/square/blue.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-91994760-1', 'auto');
ga('send', 'pageview');

</script>

</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <img src="/static/img/new-logo.png" alt="GoodCSR" style="width:180px;height:52px;">
    
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
  
    <p class="login-box-msg">Sign in to start your session</p>
    {% if messages %}
    {% for message in messages %}
    <p class="login-box-msg"><font size="3" color="red">{{message}}</font></p>
	{% endfor %}
	{% endif %}
    <form action=".{% for i in request.GET.items %}{% if forloop.counter == 1 %}?{% else %}&{% endif %}{{i.0}}={{i.1}}{% endfor %}" method="post">{% csrf_token %}
    {% if request.GET.items %}
    <input type="hidden" name="next" value="{{request.GET.items}}">
    {% endif %}
      <div class="form-group has-feedback">
        <input required='True' name="username" type="username" class="form-control" placeholder="Username" autocomplete="off">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input required='True' name="password" type="password" class="form-control" placeholder="Password" autocomplete="off">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
       <div class="g-recaptcha" data-sitekey="{{cpatcha_public_key}}"></div>
      <div class="row">
        <div class="col-xs-8">
          
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>


    <!-- /.social-auth-links -->

<!--    <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a>-->

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
<script src='https://www.google.com/recaptcha/api.js'></script>
<!-- jQuery 2.2.0 -->
<script src="/static/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/static/plugins/iCheck/icheck.min.js"></script>
</body>
</html>

templates/pdf_template.html
{% load urs_tags %}
<html>
<head>
  <title>Test</title>
  <style>
    body {
      background-color: #f7f7f7;
    }
  </style>
</head>
<body>
  <h1>Test Template</h1>
  {% for paragraph in paragraphs %}
    <p>{{ paragraph }}</p>
  {% endfor %}
  {% get_test_name p as sharp %}
  <h3>{{sharp}}</h3>
</body>
</html>

templates/sample.html
{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <title>My web site: Thanks for that!</title>
  </head>
  <body>
    
    <h1>Processing your request</h1>
    {{report_id}}
    {{slug}}
    
    
</body>
</html>
{% endblock %}

templates/test.html
<html>
<head>
  <title>Test</title>
  <style>
    body {
      background-color: #f7f7f7;
    }
  </style>
</head>
<body>
  <h1>Test Template</h1>
  {% for paragraph in paragraphs %}
    <p>{{ paragraph }}</p>
  {% endfor %}
</body>
</html>