pmu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import (dashboard,user_information)
from views.user_information import (UserInformationStorage,saveimage)
from views.login import (signin,signout,homepage,login_popup,intermidate_login,PMULoginAPI )
from views.homepage import (feedback,email_validation)
from projectmanagement.manage_roles import (projectuserslist,projectuseradd,
                                            projectuseredit)
from budgetmanagement.manage_budget import (projectbudgetadd,projectbudgetlist,
                                            projectbudgetcategoryadd,projectlineitemadd,
                                            projectbudgetdetail,budgetutilization,
                                            budgetview,year_quarter_list,
                                            budgetlineitemedit,month_quarter_list,
                                            category_listing,category_add,
                                            delete_category,category_name_validate)
from userprofile.views import *
import userprofile
from django.conf.urls import handler404, handler500
import private_storage.urls
from media.views import PrivateStorageDownloadView
handler404 = userprofile.views.handler404
handler500 = userprofile.views.handler500

admin.autodiscover()

roles_patterns = ([
    url(r'^project/role/list/$',projectuserslist),
    url(r'^project/role/add/$',projectuseradd),
    url(r'^project/role/edit/$',projectuseredit),
    url(r'^project/budget/list/$',projectbudgetlist),
    url(r'^project/budget/create/$',projectbudgetadd),
    url(r'^project/budget/category/add/$',projectbudgetcategoryadd),
    url(r'^project/budget/lineitem/add/$',projectlineitemadd),
    url(r'^project/budget/detail/$',projectbudgetdetail),
    url(r'^project/budget/report-utilization/$',budgetutilization),
    url(r'^project/budget/view/$',budgetview),
    url(r'^quarter/list/$',year_quarter_list),
    url(r'^month/list/$',month_quarter_list),
    url(r'^project/budget/lineitem/edit/$',budgetlineitemedit),
    url(r'^project/budget/category/listing/$',category_listing),
    url(r'^project/budget/add/category/$',category_add),
    url(r'^project/budget/category/delete/$',delete_category),
    url(r'project/category/exists/$',category_name_validate),

])

userroles_patterns = ([

    url(r'^list/(?P<model>(:?user|role|menu))/$', UserListView.as_view()),
    url(r'^list/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserListView.as_view()),
    url(r'^add/(?P<model>(:?role|user|menu))/$', UserAddView.as_view()),
    url(r'^add/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserAddView.as_view()),
    url(r'^edit/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserEditView.as_view()),
    url(r'^edit/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserEditView.as_view()),
    url(r'^active/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserActive.as_view()),
    url(r'^active/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserActive.as_view()),
    url(r'^manage/role/(?P<pk>\d+)/$', manage_role),
    url(r'^manage/menu/(?P<pk>\d+)/$', manage_menu),
    url(r'^manage/active/(?P<pk>\d+)/$', object_active),
])


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^dashboard/$',dashboard.admin_dashboard),
    url(r'^project/',include('projectmanagement.urls')),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^upload/',include('media.urls')),
    url(r'^report/',include('budgetmanagement.report_urls')),
    url(r'^login/$',signin),
    url(r'^$',homepage),
    url(r'^login-popup/$',login_popup),
    url(r'^feedback/$',feedback),
    url(r'^email-valid/$',email_validation),
    url(r'^managing/',include('taskmanagement.urls')),
    url(r'^manage/user-access/$',UserInformationStorage.as_view()),
    url(r'^logout/$',signout),
    url(r'^save/image/$',saveimage),
    url(r'^manage/', include(roles_patterns)),
    url(r'^usermanagement/',include(userroles_patterns)),
    url(r'^intermidate-login/', intermidate_login),
    url(r'^pmu/login/$',PMULoginAPI.as_view()),
    url(r'^private-media/$', include(private_storage.urls)),
    url(r'^private-media/(?P<path>.*)$',PrivateStorageDownloadView.as_view(),  name='serve_private_file'),
]

media/models.py
import os,datetime,urllib
from django.db import models
from django.contrib import admin
from constants import OPTIONAL
from thumbs import ImageWithThumbsField
from django.views import generic
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from ckeditor.fields import RichTextField
from budgetmanagement.models import (ReportParameter, BudgetPeriodUnit, ProjectBudgetPeriodConf, ReportMilestoneActivity)
from projectmanagement.models import (BaseContent,UserProfile, Project)
from private_storage.fields import PrivateFileField
from taskmanagement.models import (Task,Activity)
from simple_history.models import HistoricalRecords
from simple_history.admin import SimpleHistoryAdmin
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
ATTACHMENT_TYPE = ((1,'Image'),(2,'Documents'),)
DOCUMENT_TYPE = ((1,'Excel'),(2,'PDF'),(3,'PPT'),(4,'Word Document'))

def get_file_path(instance,filename):
    from budgetmanagement.models import Answer
    print type(instance)
    date = datetime.datetime.today().strftime('%Y/%m/%d')
    try:
        if isinstance(instance, Attachment):
            if instance.content_type == ContentType.objects.get(model="project"):
                proj = Project.objects.filter(id=instance.object_id).first()
                proj_slug = proj.slug
            if instance.content_type == ContentType.objects.get(model="budgetperiodunit"):
                budget_period = BudgetPeriodUnit.objects.filter(id=instance.object_id).first()
                proj_slug = budget_period.budget_period.project.slug
            if instance.content_type == ContentType.objects.get(model="projectbudgetperiodconf"):
                budget_period = ProjectBudgetPeriodConf.objects.filter(id=instance.object_id).first()
                proj_slug = budget_period.project.slug
            if instance.content_type == ContentType.objects.get(model="task"):
                task = Task.objects.filter(id=instance.object_id).first()
                proj_slug = task.activity.project.slug
            if instance.content_type == ContentType.objects.get(model="reportmilestoneactivity"):
                report_ma = ReportMilestoneActivity.objects.filter(id=instance.object_id).first()
                proj_slug = report_ma.quarter.project.project.slug
        if isinstance(instance, Note):
            proj_slug = instance.project.slug
        if isinstance(instance, Answer):
            proj = Project.objects.filter(id=instance.object_id).first()
            proj_slug = proj.slug
        return "{proj_name}/{date}/{file}".format(proj_name = proj_slug, date = date, file = filename)    
    except Exception as e:
        return "other/{date}/{file}".format(date = date, file = filename)


class Attachment(BaseContent):
    ## 
    # model to attach files.
    #content_type is a foriegn key, verbose_name- is a function differing with _"
    ## 
        
    created_by = models.ForeignKey(
        UserProfile, related_name='document_created_user', **OPTIONAL)
    attachment_file = PrivateFileField(upload_to=get_file_path,max_length=500, **OPTIONAL)
    name = models.CharField("Name", max_length=300, **OPTIONAL)
    description = models.CharField("Description", max_length=600, **OPTIONAL)
    attachment_type = models.IntegerField('ATTACHMENT_TYPE',choices=ATTACHMENT_TYPE,**OPTIONAL)
    document_type = models.IntegerField('DOCUMENT_TYPE',choices = DOCUMENT_TYPE,**OPTIONAL)
    date = models.DateTimeField(**OPTIONAL)
    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s",db_index=True, **OPTIONAL)
    object_id = models.IntegerField(_('object ID'), db_index=True, **OPTIONAL)
    relatedTo = GenericForeignKey(ct_field="content_type", fk_field="object_id")
    URL = models.URLField("Link url", max_length=200, blank=True)
    parent = models.ForeignKey('self', blank=True, null=True)
    timeline_progress = models.BooleanField(default=True)
    history = HistoricalRecords()

    def __unicode__(self):
        return str(self.id) or self.object_id

    def get_sub_documents(self):
        # 
        try:
            subdocuments = Attachment.objects.filter(active=2,parent=self)
            documents = [{'name':i.name,'file':PHOTO_URL+'/'+i.organisationdocument.document.url} for i in subdocuments]
        except:
            documents = []
            # 
        return documents

    def get_file_keywords(self):
        # 
        keywords = FileKeywords.objects.filter(active=2,object_id=self.id,content_type=ContentType.objects.get(model='Attachment')).values_list('key',flat=True)
        key_list = Keywords.objects.filter(id__in=keywords).values_list('name',flat=True)
        # 
        return list(key_list)

#    def __init__(self,*args, **kwargs):
#        pass
#        #global_variables(request)
class Keywords(BaseContent):
    name = models.CharField(max_length=100, **OPTIONAL)

    def __unicode__(self):
        return self.name or ''
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
class FileKeywords(BaseContent):
    key = models.ForeignKey(Keywords, **OPTIONAL)
    order_no = models.IntegerField(default=0)
    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s",**OPTIONAL)
    object_id = models.IntegerField(**OPTIONAL)

    def __unicode__(self):
        return self.key.name or ''

LOCATION_TYPE = ((0, 'Urban'), (1, 'Semi-urban'), (2, 'Rural'))
# 
class ProjectLocation(BaseContent):
    # 
    location = models.ForeignKey("projectmanagement.Boundary", **OPTIONAL)
    created_by = models.ForeignKey('projectmanagement.UserProfile', **OPTIONAL)
    area = models.CharField(max_length=200, **OPTIONAL)
    ward_no = models.CharField(max_length=50, **OPTIONAL)
    pin_code = models.CharField(max_length=50, **OPTIONAL)
    program_type = models.IntegerField(choices = LOCATION_TYPE, default=0)
    content_type = models.ForeignKey(ContentType,null=True,blank=True, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s")
    object_id = models.IntegerField(_('object ID'),null=True,blank=True)
    relatedTo = GenericForeignKey(ct_field="content_type", fk_field="object_id")

    def __unicode__(self):
        return str(self.id)
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
class Comment(BaseContent):
    text = models.TextField(**OPTIONAL)
    created_by = models.ForeignKey(
        UserProfile, related_name='comment_created_user', **OPTIONAL)
    content_type = models.ForeignKey(ContentType,null=True,blank=True, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s")
    object_id = models.IntegerField(_('object ID'),null=True,blank=True)
    relatedTo = GenericForeignKey(ct_field="content_type", fk_field="object_id")
# 
class Article(BaseContent):
    name = models.CharField("Name", max_length=300, **OPTIONAL)
    description = models.TextField(**OPTIONAL)
    listing_order = models.IntegerField(default=0, **OPTIONAL)
    parent = models.ForeignKey('self', **OPTIONAL)
    slug = models.SlugField(_("Slug"), blank=True)
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
class Section(BaseContent):
    # 
    name = models.CharField("Name", max_length=300, **OPTIONAL)
    description = RichTextField(**OPTIONAL)
    summary = RichTextField(**OPTIONAL)
    article = models.ForeignKey('Article', **OPTIONAL)
    cover_image = ImageWithThumbsField(upload_to='static/%Y/%m/%d', sizes=((90,120),(360,480)),blank=True,null=True,help_text="Image size should be 930x300 pixels")
    image = ImageWithThumbsField(upload_to='static/%Y/%m/%d', sizes=((90,120),(360,480)),blank=True,null=True,help_text="Image size should be 930x300 pixels")
    listing_order = models.IntegerField(default=0, blank=True, null=True)
    slug = models.SlugField(_("Slug"), blank=True)
# 
class ContactPersonInformation(BaseContent):
    name = models.CharField("Name", max_length=300, **OPTIONAL)
    email = models.CharField("Email", max_length=500, **OPTIONAL)
    organization_name = models.CharField("Organization Name", max_length=600, **OPTIONAL)
    mobile_number = models.CharField("Mobile Number", max_length=50, **OPTIONAL)
    message = models.TextField(**OPTIONAL)
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
IMAGE_TYPE = ((1,'Pie-Image'),(2,'Gatt-image'),)
class ScreenshotMedia(BaseContent):

    report_parameter = models.ForeignKey(ReportParameter,**OPTIONAL)

templates/attachment/listing.html
{% extends 'project/project-summary.html' %}
{% load urs_tags roles_tags %}

{% block content %}
<style>
.budget_button{background: #00998b; border: 0px; color:#fff; padding:3px 10px; border-radius:3px;}
</style>
<script>
function exportToForm(){
  var selectedText = document.getElementById("activate_tagator2").value;
  $("#dest tr.data_row").each(function(){
    if ($(this).text().search(new RegExp(selectedText, "i")) < 0) {
        $(this).fadeOut();
     } else {
         $(this).show();
    }
});

}
</script>
<!--Green pad Ends-->
<!--Content part starts-->
<section class="content-part forms_section">

	<div class="row">
	<div class="content-top">
      <div class="select-area search_area">
      	<label>Search</label>
   
		<input id="activate_tagator2" type="text" class="form-control" placeholder="Name or Type" data-tagator-show-all-options-on-focus="true" data-tagator-autocomplete="['Budget', 'Report', 'Document', 'Files', 'Budget', 'Report', 'Document', 'Task', 'Worksheet']">
        <img onclick="javascript:exportToForm()" src="/static/img/search-icon.png">
         </div>
        <!--<form>
          <div class="multiselect">
            <div class="selectBox" onclick="showCheckboxes()">
              <select class="select_box">
                <option>Sep-Dec</option>
              </select>
              <div class="overSelect"></div>
            </div>
            <div id="checkboxes">
              <label for="one">
                <input type="checkbox" id="one" />Jan-Mar</label>
              <label for="two">
                <input type="checkbox" id="two" />Apr-Jul</label>
              <label for="three">
                <input type="checkbox" id="three" />Aug-Sep</label>
              <label for="three">
                <input type="checkbox" id="three" />Oct-Dec</label>  
            </div>
          </div>
        </form>-->
       
    </div>
    <div class="white-box white-pad"><div style="float: right;">
      {% get_user_permission request as user_obj %}
            {% with "files"|make_string:"add" as keystring %}
            {% if request.user.is_superuser or request|has_permission_for_action:keystring %}
                  <a class="budget_button" href="/upload/doc/?model=Project&slug={{slug}}&key=2">Add Image</a>
                  <a class="budget_button" href="/upload/doc/?model=Project&slug={{slug}}&key=1">Add Document</a>
      {% endif %}
      {% endwith %}
    </div>
    <div class="table-responsive">
    	<table class="table table-striped table-bordered sort_table" id="dest">
  <thead>
    <tr>
      <th>File</th>
      <th style="width: 10%;">File Title</th>
      <th>File Description</th>
      <th>File Type</th>
      <!-- <th>Uploadaed by</th> -->
      <th>Tags</th>
      <!-- <th>Source</th> -->
      <th>Upload Date </th>
            {% with "files"|make_string:"edit" as keystring %}
            {% if request.user.is_superuser or request|has_permission_for_action:keystring %}
      <th>Manage </th>
      {% endif %}
      {% endwith %}
    </tr>
  </thead>
  <tbody>
    {% for i in attachment %}
    <tr class="data_row">
      <td align="center">
      {% if i.attachment_type == 2 %}
        {% if i.document_type == 1 %}<!-- excel -->
        {% if i.attachment_file %}
        <a href="{{image}}{{i.attachment_file.url}}" download>{% endif %}<img src="/static/img/excell-color.jpg" height=128px width=128px></a>
        {% endif %}
        {% if i.document_type == 2 %}<!-- pdf -->
        {% if i.attachment_file %}
        <a href="{{image}}{{i.attachment_file.url}}" download>{% endif %}<img src="/static/img/pdf.jpg" height=128px width=128px></a>
        {% endif %}
        {% if i.document_type == 3 %}<!-- ppt -->
        {% if i.attachment_file %}
        <a href="{{image}}{{i.attachment_file.url}}" download>{% endif %}<img src="/static/img/wordpress.jpg" height=128px width=128px></a>
        {% endif %}
        {% if i.document_type == 4 %}<!-- doc -->
        {% if i.attachment_file %}
        <a href="{{image}}{{i.attachment_file.url}}" download>{% endif %}<img src="/static/img/excell-black.jpg" height=128px width=128px></a>
        {% endif %}
        {% else %}

        {% if i.attachment_file %}<a href="{{image}}{{i.attachment_file.url}}" download><img src="{{image}}{{i.attachment_file.url}}" height=128px width=128px>{% else %}<img src="" height=128px width=128px>{% endif %}{% endif %}</td></a>
      <td align="center" style="width: 10%;"><!-- <a href="/upload/edit/?model=Project&obj_id={{i.object_id}}&id={{i.id}}"> -->{% if i.name %}{{i.name}}{% else %}-{% endif %} <!-- </a> --></td>
      <td align="center">{{i.description}}</a></td>
      <td align="center">{{i.get_attachment_type_display}} {% if i.attachment_type == 2 %} ({{i.get_document_type_display}}) {% endif %}</td>
      <!-- <td>{{i.created_by.user.first_name}} {{i.created_by.user.last_name}}</td> -->
        <td align="center"><div class="span_bottom">{% for j in i.get_file_keywords %}<span>{{j}} </span>{% endfor %}<!-- <span>Budget</span><span>Report</span><span>Document</span><span>Files</span> --></div class="span_bottom"></td>

        
      <!-- <td>Task: Dhenuki Labours Unit</td> -->
      <td align="center">{{i.created}}</td>
      {% with "files"|make_string:"edit" as keystring %}
            {% if request.user.is_superuser or request|has_permission_for_action:keystring %}
      <td align="right">
        {% get_user_permission request as user_obj %}
            {% pmo_role request as pmo_access %}
                {% if user_obj.is_admin_user == True or user_obj.organization_type == 1 or pmo_access == 1 %}
       <a class="budget_button" href="/upload/edit/?model=Project&obj_id={{i.object_id}}&id={{i.id}}&slug={{slug}}"> Edit</a> <a class="btn btn-danger delete_function" href="/project/remove/record/?id={{i.id}}&model=Attachment&slug={{slug}}" onclick="return confirm('Are you sure you want to Delete - {{i.name}}')">X</button></a>
       {% endif %} </td>
       {% endif %} {% endwith %}
      <!-- <td align="center"><a class="budget_button" href="/upload/edit/?model=Project&obj_id={{i.object_id}}&id={{i.id}}"> Edit</a></td> -->
    </tr>
      <!-- <td align="center"><a class="budget_button" href="/upload/edit/?model=Project&obj_id={{i.object_id}}&id={{i.id}}"> Edit</a></td> -->
    </tr>
    {% endfor %}

  </tbody>
</table>
        </div>
          <div class="pagination_no">
        <div id="pagination-long"></div>
    </div>
    </div>
    
    
    
    </div>
</section>
<!--Content part Ends-->
{% endblock %}

<!-- jQuery (necessary for JavaScript plugins) -->
<script type="text/javascript" src="js/jquery.selectbox-0.2.js"></script>


    
<script type="text/javascript" src="/static/js/ddsmoothmenu.js"></script>
<script type="text/javascript" src="/static/js/jquery.mmenu.min.all.js"></script>
<script type="text/javascript" src="/static/js/common.js" /></script>

<!--<script type="text/javascript" src="js/jquery.scrollbox.js"></script>-->
<script src="/static/js/jquery.nicescroll.min.js"></script>

<script type="text/javascript">
alert("aaaa");
    $(function () {
        $("#activate_tagator2").change(function () {
            alert(this);
            var selectedText = $(this).text();
            var selectedValue = $(this).val();
            
            
            $("#dest tr.data_row").each(function(){
            if (selectedText == "Super Category"){
                $(this).show();
            }
            else{
            if ($(this).text().search(new RegExp(selectedText, "i")) < 0) {
                $(this).fadeOut();
             } else {
                 $(this).show();
            }
            }
        });
            
        });
    });
</script>
<script>
//Toggle
		
		 $('.user-menu').on('click',function(){
          $('.dropdown-menu').slideToggle();
          
        });
		 $(document).ready(function(e) {	
	/*Content Show/Hide */
	$('.hide-cont').hide();
	$('.close-cont').hide();
	$('.view-cont').click(function(){
		$('.hide-cont').slideDown(350);
		$('.close-cont').show();
		$('.view-cont').hide();
	});
	$('.close-cont').click(function(){
		$('.hide-cont').slideUp(350);
		$('.close-cont').hide();
		$('.view-cont').show();
	});	
 });
	
</script>

    <script type="text/javascript">
   
	
	var expanded = false;

function showCheckboxes() {
  var checkboxes = document.getElementById("checkboxes");
  if (!expanded) {
    checkboxes.style.display = "block";
    expanded = true;
  } else {
    checkboxes.style.display = "none";
    expanded = false;
  }
}
    </script>
    <script>
  $(document).ready(function() {
  
	var nice = $("html").niceScroll();  // The document page (body)
	
	$("#div1").html($("#div1").html()+' '+nice.version);
    
    $("#boxscroll, .table-resp tbody").niceScroll({cursorborder:"",cursorcolor:"#949494",boxzoom:true}); // First scrollable DIV

    
  });
</script>
<!--  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="crossorigin="anonymous"></script>-->
<script src="/static/js/materialize-pagination.js"></script>
    <script>
    $(function() {
        $(function() {
            $('#pagination-long').materializePagination({
                align: 'center',
                lastPage: 10,
                firstPage: 1,
                useUrlParameter: false,
                onClickCallback: function(requestedPage) {
                    //console.log('Requested page from #pagination-long: ' + requestedPage);
                }
            });
        });
    });
    </script>
<script src="js/sorttable.js"></script>

<script>
$(function(){
	$("#dest").addSortWidget();
});
</script>

    
    <script src="/static/js/fm.tagator.jquery.js"></script>
	<script>
		$(function () {
			var $input_tagator1 = $('#input_tagator1');
			var $activate_tagator1 = $('#activate_tagator1');
			$activate_tagator1.click(function () {
				if ($input_tagator1.data('tagator') === undefined) {
					$input_tagator1.tagator({
						autocomplete: ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth'],
						useDimmer: true
					});
					$activate_tagator1.val('destroy tagator');
				} else {
					$input_tagator1.tagator('destroy');
					$activate_tagator1.val('activate tagator');
				}
			});
			$activate_tagator1.trigger('click');
		});
	</script>
<link rel="stylesheet" href="/static/css/jquery.fancybox.css" type="text/css" media="screen" />
<script type="text/javascript" src="/static/js/jquery.fancybox.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    $(".iframe").fancybox({
        type: 'iframe'
    });
});
</script>


</body>
</html>
