pmu/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import (dashboard,user_information)
from views.user_information import (UserInformationStorage,saveimage)
from views.login import (signin,signout,homepage,login_popup,intermidate_login,PMULoginAPI )
from views.homepage import (feedback,email_validation)
from projectmanagement.manage_roles import (projectuserslist,projectuseradd,
                                            projectuseredit)
from budgetmanagement.manage_budget import (projectbudgetadd,projectbudgetlist,
                                            projectbudgetcategoryadd,projectlineitemadd,
                                            projectbudgetdetail,budgetutilization,
                                            budgetview,year_quarter_list,
                                            budgetlineitemedit,month_quarter_list,
                                            category_listing,category_add,
                                            delete_category,category_name_validate)
from userprofile.views import *
import userprofile
from django.conf.urls import handler404, handler500
import private_storage.urls
from media.views import PrivateStorageDownloadView
handler404 = userprofile.views.handler404
handler500 = userprofile.views.handler500

admin.autodiscover()

roles_patterns = ([
    url(r'^project/role/list/$',projectuserslist),
    url(r'^project/role/add/$',projectuseradd),
    url(r'^project/role/edit/$',projectuseredit),
    url(r'^project/budget/list/$',projectbudgetlist),
    url(r'^project/budget/create/$',projectbudgetadd),
    url(r'^project/budget/category/add/$',projectbudgetcategoryadd),
    url(r'^project/budget/lineitem/add/$',projectlineitemadd),
    url(r'^project/budget/detail/$',projectbudgetdetail),
    url(r'^project/budget/report-utilization/$',budgetutilization),
    url(r'^project/budget/view/$',budgetview),
    url(r'^quarter/list/$',year_quarter_list),
    url(r'^month/list/$',month_quarter_list),
    url(r'^project/budget/lineitem/edit/$',budgetlineitemedit),
    url(r'^project/budget/category/listing/$',category_listing),
    url(r'^project/budget/add/category/$',category_add),
    url(r'^project/budget/category/delete/$',delete_category),
    url(r'project/category/exists/$',category_name_validate),

])

userroles_patterns = ([

    url(r'^list/(?P<model>(:?user|role|menu))/$', UserListView.as_view()),
    url(r'^list/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserListView.as_view()),
    url(r'^add/(?P<model>(:?role|user|menu))/$', UserAddView.as_view()),
    url(r'^add/(?P<model>(:?roleconfig))/(?P<pid>\d+)/$', UserAddView.as_view()),
    url(r'^edit/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserEditView.as_view()),
    url(r'^edit/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserEditView.as_view()),
    url(r'^active/(?P<model>(:?role|user|menu|roleconfig))/(?P<pk>\d+)/$', UserActive.as_view()),
    url(r'^active/(?P<model>(:?roleconfig))/(?P<pk>\d+)/(?P<pid>\d+)/$', UserActive.as_view()),
    url(r'^manage/role/(?P<pk>\d+)/$', manage_role),
    url(r'^manage/menu/(?P<pk>\d+)/$', manage_menu),
    url(r'^manage/active/(?P<pk>\d+)/$', object_active),
])


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^dashboard/$',dashboard.admin_dashboard),
    url(r'^project/',include('projectmanagement.urls')),
    url(r'^dashboard/',include('dashboard.urls')),
    url(r'^upload/',include('media.urls')),
    url(r'^report/',include('budgetmanagement.report_urls')),
    url(r'^login/$',signin),
    url(r'^$',homepage),
    url(r'^login-popup/$',login_popup),
    url(r'^feedback/$',feedback),
    url(r'^email-valid/$',email_validation),
    url(r'^managing/',include('taskmanagement.urls')),
    url(r'^manage/user-access/$',UserInformationStorage.as_view()),
    url(r'^logout/$',signout),
    url(r'^save/image/$',saveimage),
    url(r'^manage/', include(roles_patterns)),
    url(r'^usermanagement/',include(userroles_patterns)),
    url(r'^intermidate-login/', intermidate_login),
    url(r'^pmu/login/$',PMULoginAPI.as_view()),
    url(r'^private-media/$', include(private_storage.urls)),
    url(r'^private-media/(?P<path>.*)$',PrivateStorageDownloadView.as_view(),  name='serve_private_file'),
]

taskmanagement/urls.py
from django.conf.urls import url
from .views import *
from .forms import *
from .manage_task import *

# URLS for Task management
# 
urlpatterns = [
#    url(r'^(?P<model_name>.*)/listing/$',listing),
    url(r'^listing/$',listing),
#    url(r'^tasks/updates/(?P<obj_id>.*)/(?P<slug>.*)/$',taskdateupdates),
    url(r'^(?P<model_name>[\w-]+)/(?P<m_form>[\w-]+)/add/$',add_taskmanagement),
    url(r'^(?P<model_name>[\w-]+)/(?P<m_form>[\w-]+)/edit/(?P<slug>.+)/$',edit_taskmanagement),
    url(r'^(?P<model_name>[\w-]+)/status/',active_change),
    url(r'^task/dependencies/$',task_dependencies),
    url(r'^milestone/overdue/$',milestone_overdue),
    url(r'^tasks/auto-computation/date/$',task_auto_computation_date),
    url(r'^my-tasks/details/$',my_tasks_details),
    url(r'^my-calendar/details/$',my_tasks_details),
    url(r'^tasks/expected-date/caluclator/$',get_tasks_objects),
    url(r'^gantt-chart-data/$', GanttChartData.as_view()),
    #url(r'^my-tasks/updates/(?P<obj_id>.*)$',task_comments),
    url(r'^my-tasks/updates/$',task_comments),
    url(r'^activites/$',get_activites_list),
    url(r'supercategories/selected/$',get_super_selected),
    url(r'activities/selected/$',get_activity_selected),
    url(r'^activity/related/tasks/$',get_activity_tasks),
    url(r'^task/remove/$',remove_task),
    url(r'^(?P<model_name>[\w-]+)/(?P<m_form>[\w-]+)/addactivity/$',add_activitymanagement),
    url(r'^(?P<model_name>[\w-]+)/(?P<m_form>[\w-]+)/addmilestone/$',add_milestonemanagement),
    
#    url(r'^tasks/maximum/end_date/$',tasks_max_end_date),
    
#    url(r'^tasks/updates/(?P<obj_id>.*)/$',taskdateupdates),
]

# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.

taskmanagement/models.py
from django.db import models
from django.utils.encoding import smart_str, smart_unicode
from projectmanagement.manager import ActiveQuerySet
from django.template.defaultfilters import slugify
from constants import  OPTIONAL
import six
from django.contrib import admin
from django.views import generic
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericForeignKey
from simple_history.models import HistoricalRecords
from thumbs import ImageWithThumbsField
from simple_history.admin import SimpleHistoryAdmin
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from projectmanagement.models import BaseContent

#----------------------introduction------------------------------------------#
# Task Management is the application where database tables are related to Activity,Task,Milestone
#--------------------ends here--------------------------------------------------#

ACTIVITY_CHOICES = ((1,'Core'),(2,'Non-core'),)
STATUS_CHOICES = ((0,' '),(1, 'Open'), (2, 'Close'), (3, 'Ongoing'),)

# Activity model
class Activity(BaseContent):
    project = models.ForeignKey("projectmanagement.Project",**OPTIONAL)
    super_category = models.ForeignKey("budgetmanagement.SuperCategory",**OPTIONAL)
    name = models.CharField(max_length=600,**OPTIONAL)
    activity_type = models.IntegerField(choices = ACTIVITY_CHOICES,default=1)
    status = models.IntegerField( choices = STATUS_CHOICES,default=0)
    description = models.TextField(**OPTIONAL)
    created_by = models.ForeignKey("projectmanagement.UserProfile",related_name ='activity_created_user',blank=True,null=True)
    assigned_to = models.ForeignKey("projectmanagement.UserProfile",related_name ='activity_asigned_user',blank=True,null=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'activity_subscriber_user',blank=True )
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), related_name="content_type_set_for_%(class)s",**OPTIONAL)
    object_id = models.IntegerField(_('object ID'),**OPTIONAL)
    relatedTo = GenericForeignKey(ct_field="content_type", fk_field="object_id")
    history = HistoricalRecords()
    
    def __str__(self):
        return str(self.name)
    def __unicode__(self):
        return unicode(self.name)

# task model
class Task(BaseContent):
    name = models.CharField(max_length=600,**OPTIONAL)
    activity = models.ForeignKey(Activity)
    start_date=models.DateTimeField(**OPTIONAL)
    end_date=models.DateTimeField(**OPTIONAL)
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    actual_start_date = models.DateTimeField(**OPTIONAL)
    actual_end_date = models.DateTimeField(**OPTIONAL)
    status = models.IntegerField(choices = STATUS_CHOICES,default=0)
    task_dependency = models.ManyToManyField('self',blank=True,symmetrical=False)
    created_by = models.ForeignKey("projectmanagement.UserProfile",related_name ='task_created_user',**OPTIONAL)
    assigned_to = models.ForeignKey("projectmanagement.UserProfile",related_name ='task_assigned_user',blank=True,null=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'task_subscriber_user',blank=True )
    task_progress = models.CharField(max_length=100,**OPTIONAL)
    history = HistoricalRecords()

    def __str__(self):
        return smart_str(self.name) or ''
    def __unicode__(self):
        return unicode(self.name)

    def is_dependent(self):
        task = Task.objects.filter(task_dependency = self.id)
        if task:
            return True
        else :
            return False
    
    def task_attachments(self):
        inner_attach=[]
        from datetime import datetime
        from media.models import Attachment,Comment
        comment = Comment.objects.filter(active=2,content_type=ContentType.objects.get(model=('task')),object_id=self.id).order_by('-id')
        comment_dates = list(set([i.date() for i in comment.values_list('created',flat=True)]))
        task_progress_history = self.history.filter(task_progress__isnull=False).order_by('-id')
        attachments = Attachment.objects.filter(active=2,content_type=ContentType.objects.get(model=('task')),object_id=self.id).order_by('-id')
        attach_dates = list(set([i.date() for i in attachments.values_list('modified',flat=True)]))
        task_progress_dates = list(set([i.date() for i in task_progress_history.values_list('modified',flat=True)]))
        
        distinct_dates = attach_dates + comment_dates + task_progress_dates
        
        attach = []
        if distinct_dates:
            for date in list(set(distinct_dates)):
                inner_attach =[]
                for i in attachments.filter(created__range = (datetime.combine(date, datetime.min.time()),datetime.combine(date, datetime.max.time()))):
                    inner_attach.append(i)
                attach.append({date:inner_attach})
            attach = sorted(attach, key=lambda key: key,reverse=True)
        else:
            attach=[]
        return attach

# milestone model
class Milestone(BaseContent):
    project = models.ForeignKey("projectmanagement.Project",**OPTIONAL)
    name = models.CharField(max_length=300,**OPTIONAL)
    task = models.ManyToManyField(Task,blank=True)
    overdue = models.DateTimeField(**OPTIONAL)
    status = models.IntegerField(choices = STATUS_CHOICES,default=0)
    slug = models.SlugField(_("Slug"), max_length=600,blank=True)
    subscribers = models.ManyToManyField("projectmanagement.UserProfile",related_name = 'milestone_subscriber_user',blank=True )
    history = HistoricalRecords()
    def __str__(self):
        return smart_str(self.name)
    def __unicode__(self):
        return unicode(self.name)

# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.


# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
 # When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.
 # When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast. 
# When working with any programming language, you include comments
# in the code to notate your work. This details what certain parts 
# know what you were up to when you wrote the code. This is a necessary
# practice, and good developers make heavy use of the comment system. 
# Without it, things can get real confusing, real fast.

templates/taskmanagement/edit_task.html
{% extends 'base.html' %}

{% block section %}
<div> </div>
{% endblock %}




{% block content %}
<style>
    .error li{ color :red;}
    .errorlist li{color :red;}
    #date_error,#min_max {color : red;}
</style>
<div class="clear"></div>
<section class="content-part">
    <div class='container' >
	<div class="white-box">
	{%if message %}
	    <h3 class border_linr">Please add <a style="text-decoration:underline;color:#169776" href= '/manage/project/budget/create/?slug={{project.slug}}'>Budget</a>  for the project before proceeding with adding Activities / Tasks or Milestone </h3>
	{% else %}
    <form class="form-horizantal budget_form" action=".?slug={{project.slug}}" method='POST' enctype="multipart/form-data" novalidate>{% csrf_token %}
     <div class="col-md-12">
        {% if slug %}
                   <h3 class="border_line">Edit {{model_name}}</h3>
                  {% else %}
                     <h3 class="border_line">Add {{model_name}}</h3>
                  {% endif %}
        </div>
       <div class="col-md-6 nopadding">
            <form action="{{request.path}}" id= "ic_form" method='POST' enctype="multipart/form-data">{% csrf_token %}
                {{form.non_fields_errors}}
        
                    {{form.media}}
                    {% for field in form %}
                        <div class="col-md-12">
                            <div class="form-group" id= "{{field.name}}">
                                
                                <label>{{field.label_tag}}</label>
                                {{field}}
                                {{field.errors}}
                            </div>
                        </div>
                    {% endfor %}
            <input id = 'slug' name = 'slug_project' type='hidden' value = "{{project.slug}}"/>
           <div class="col-md-12">
            <div class="form-group">
              <input class="budget_button" type="submit" value="Submit"/>
              <a class="btn btn-success" href="/managing/listing/?slug={{project.slug}}&key=task-milestone" style="margin-right:5px;float: right;">Cancel</button></a>
            </div>
           </div>
        </div>
    </form>
    {% endif %}
    
    </div>
    </div>
</section>
<!--Content part Ends-->
{% endblock %}
<!--Footer starts-->


</div>


{% block script %}
<!-- jQuery (necessary for JavaScript plugins) -->
<link href="/static/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/static/js/jquery.selectbox-0.2.js"></script>
<script type="text/javascript" src="/static/js/ddsmoothmenu.js"></script>
<script type="text/javascript" src="/static/js/jquery.mmenu.min.all.js"></script>
<script type="text/javascript" src="/static/js/common.js" /></script>
<script src="/static/js/fSelect.js"></script>
<!--<script type="text/javascript" src="js/jquery.scrollbox.js"></script>-->
<script src="/static/js/jquery.nicescroll.min.js"></script>
<script src = "/static/js/jquery.multi-select.js"></script>
<script src="/static/js/bootstrap-multiselect.js"></script>
<script>
//Toggle
		
		 $('.user-menu').on('click',function(){
          $('.dropdown-menu').slideToggle();
          
        });
		 $(document).ready(function(e) {	
	/*Content Show/Hide */
	$('.hide-cont').hide();
	$('.close-cont').hide();
	$('.view-cont').click(function(){
		$('.hide-cont').slideDown(350);
		$('.close-cont').show();
		$('.view-cont').hide();
	});
	$('.close-cont').click(function(){
		$('.hide-cont').slideUp(350);
		$('.close-cont').hide();
		$('.view-cont').show();
	});	
 });
	
</script>

    <script type="text/javascript">
   
	
	var expanded = false;

function showCheckboxes() {
  var checkboxes = document.getElementById("checkboxes");
  if (!expanded) {
    checkboxes.style.display = "block";
    expanded = true;
  } else {
    checkboxes.style.display = "none";
    expanded = false;
  }
}
    </script>
    <script>
  $(document).ready(function() {
  
	var nice = $("html").niceScroll();  // The document page (body)
	
	$("#div1").html($("#div1").html()+' '+nice.version);
    
    $("#boxscroll, .table-resp tbody").niceScroll({cursorborder:"",cursorcolor:"#949494",boxzoom:true}); // First scrollable DIV

    
  });
</script>
<script src="/static/js/bootstrap.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
<script>
    $(document).ready(function() {
        $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true});
        //$( "#id_start_date" ).datepicker({ dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true });
        $( "#id_end_date" ).datepicker({ dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true });
        $( "#id_actual_start_date" ).datepicker({ dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true });
        $( "#id_actual_end_date" ).datepicker({ dateFormat: 'yy-mm-dd',changeMonth: true,changeYear: true });
        $(".hasDatepicker").keyup(function(e) {if(e.keyCode == 8 || e.keyCode == 46) { $.datepicker._clearDate(this); }});
        });
</script>


<script>
    $(document).ready(function() {
        var add = '{{add}}'
        if (add == 'True'){
            $('.test').fSelect();
        }
        $("#id_description").addClass('form-control text_area');
    });
</script>









<script>
    $(document).ready(function() {
    $('#id_activity').on('change',function(e){
        
        var select_id = $('#id_activity').val();
        $.ajax({
            url:'/managing/task/dependencies/',
            type:'GET',
            data:{id:select_id},
            dataType:"json",
            success:function(data){
                if (data.project_start_date != ""){
                    document.getElementById("id_start_date").value = data.project_start_date;
                 }
            },
            error : function(){}
        });
        e.stopImmediatePropagation();
        return false;
      });
    });
</script>

<script>
///managing/tasks/expected-date/caluclator/
    $(document).ready(function() {
    if ('{{model_name}}' == 'Task'){
    
    $('#id_super_category').on('change',function(e){
        var dependency_id = $('#id_super_category').val();
        $.ajax({
            url:'/managing/activites/',
            type:'GET',
            data:{'id':JSON.stringify(dependency_id)},
            dataType:"json",
            success:function(data){
            var act = $('#id_activity').val();
                $('#id_activity option').remove();
                $('#id_activity').append('<option value="" >-----</option>')
                if (data.activity){
                    activity = data.activity
                   for (var i=0;i<activity.length;i++){
                    $('<option value="'+ activity[i]['id']+'">' + activity[i]['name'] +' ('+activity[i]['super_name']+')'+ '</option>').appendTo('#id_activity');
                    }
                    $('#id_activity').val(act);
                }
            
            },
            error : function(){}
        });
        e.stopImmediatePropagation();
        return false;
      });
    }
    });
    
    
</script>

<script>
$(document).ready(function(){
var count=0;
    $('#id_task_dependency').on('change',function(){
    if(count==0){
        count = count+1;
        }
    else{
        var dependency_id = $('#id_task_dependency').val();
            $.ajax({
                url:'/managing/tasks/expected-date/caluclator/',
                type:'GET',
                data:{'id':JSON.stringify(dependency_id)},
                dataType:"json",
                success:function(data){
                if (data.calculation != ""){
                    document.getElementById("id_start_date").value = data.calculation;
                    var date = data.calculation
                    //$( "#id_start_date" ).datepicker({ dateFormat: 'yy-mm-dd',minDate: date,changeMonth: true,changeYear: true });
                    $( "#id_start_date" ).datepicker("option", "minDate", date);
                 }
                },
                error : function(){}
            });
      
      }
    });
      
      
});
</script>
<script>
 
</script>


<script>
$(document).ready(function() {
	var p_sd = "{{project_startdate}}";
	var dependency_task = "{{is_dependent}}";
    if ("{{model_name}}"=="Task"){
    if ($("id_start_date").val()!=''){
              var start_date = "{{form.start_date.value|date:'Y-m-d'}}"
              document.getElementById("id_start_date").value = start_date
              if (dependency_task == 'true'){
              $( "#id_start_date" ).datepicker({ dateFormat: 'yy-mm-dd',minDate: start_date,changeMonth: true,changeYear: true });
              }
              else{
              $( "#id_start_date" ).datepicker({ dateFormat: 'yy-mm-dd',minDate: p_sd,changeMonth: true,changeYear: true });
              }
              
          }
    if ($("id_end_date").val()!=''){
              var start_date = "{{form.end_date.value|date:'Y-m-d'}}"
              document.getElementById("id_end_date").value = start_date
          }
    if ($("id_actual_start_date").val()!=''){
              var actual_start_date = "{{form.actual_start_date.value|date:'Y-m-d'}}"
              document.getElementById("id_actual_start_date").value = actual_start_date
          }
    if ($("id_actual_end_date").val()!=''){
              var actual_end_date = "{{form.actual_end_date.value|date:'Y-m-d'}}"
              document.getElementById("id_actual_end_date").value = actual_end_date
          }
    }
    $(".hasDatepicker").keyup(function(e) {if(e.keyCode == 8 || e.keyCode == 46) { $.datepicker._clearDate(this); }});
});
</script>

<script>
    $(document).ready(function() {
        if ('{{m_form}}' != 'ActivityForm'){ 
        var activity = $('#id_activity').val();
        $.ajax({
            url:'/managing/supercategories/selected/',
            type:'GET',
            data:{'id':activity,'form':'TaskForm'},
            dataType:"json",
            success:function(data){
            
            var categories = data.super_categories
            $("#id_super_category").val(categories);
            $('.test').fSelect();
            $("#id_activity").val(activity);
            
            },
        });
        return false;
      }
    });
</script>
    
<script>
    $(document).ready(function() { 
        $('#id_subscribers').fSelect(); 
        if ('{{m_form}}' != 'ActivityForm'){
        var tasks = $('#id_task').val();
        $.ajax({
            url:'/managing/activities/selected/',
            type:'GET',
            data:{'id':JSON.stringify(tasks)},
            dataType:"json",
            success:function(data){
                $("#id_activity").val(data.activity);
                var activity = $("#id_activity").val();
                $.ajax({
                url:'/managing/supercategories/selected/',
                type:'GET',
                data:{'id':JSON.stringify(activity),'form':'MilestoneForm'},
                dataType:"json",
                success:function(data){
                        var categories = data.super_categories
                        $("#id_super_category").val(categories);
                        $('.test').fSelect();
                        },
                    });
                    return false;
            },
        });
        return false;
      }
    });
</script>

<script>
$(document).ready(function() {
    var start_date = $('#id_start_date').val();
    var end_date = $('#id_end_date').val();
    if (start_date == null || start_date == ''){
        $('#id_activity').trigger('change');
        $('#id_task_dependency').trigger('change');
    }
  });


</script>
<script>
$(document).ready(function() {
    if ('{{form.errors}}'){
        var end_date = '{{end_date}}'
        var actual_end_date = '{{actual_end_date}}'
        var actual_start_date = '{{actual_start_date}}'
        document.getElementById("id_actual_end_date").value = actual_end_date
        document.getElementById("id_actual_start_date").value = actual_start_date
        document.getElementById("id_end_date").value = end_date
    }
});
</script>
<script >
/*
$(document).ready(function() {
    $('#id_name').keypress(function( e ){
        var k;
        document.all ? k = e.keyCode : k = e.which;
        return ((k >= 65 && k < 91) || (k > 96 && k < 123) || k == 8 || k == 32 ||(k >= 38 && k <= 41) || (k>=44 && k<=46));
        }
     ).on('paste', function (e) {
        var k;
        document.all ? k = e.keyCode : k = e.which;
        return ((k >= 65 && k < 91) || (k > 96 && k < 123) || k == 8 || k == 32 ||(k >= 38 && k <= 41) || (k>=44 && k<=46));
        }
        );
  });
  */
$(document).ready(function() {
    $('#id_name').keypress(function( e ){
        var k;
        document.all ? k = e.keyCode : k = e.which;
        return ((k >= 65 && k < 91) || (k > 96 && k < 123) || k == 8 || k == 32 ||(k >= 38 && k <= 41) || (k>=44 && k<=46));
        }
     )
  });
  
  $('#id_description').keypress(function (e) {
    var regex = new RegExp("^[a-zA-Z0-9]+$");
    var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
    if (regex.test(str)) {
        return true;
    }

    e.preventDefault();
    return false;
}).on('paste', function (e) {
  var regex = new RegExp("^[a-zA-Z0-9]+$");
    var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
    if (regex.test(str)) {
        return true;
    }

    e.preventDefault();
    return false;
});
    </script>

{% endblock %}

templates/taskmanagement/taks_completed.html
{% extends 'base.html' %}

{% block content %}

<div class="white-box">
    	<div class="left-white">
        	<h2>Task and Progress Completion</h2><br>
        	<div>
            <h3 color ='green'>completed {{completed_tasks}} tasks</h2><br>
            <h3 color = 'blue'> of {{total_tasks}} </h3><br>
            <h2 color = 'orange'> under {{total_milestones}} Milestones</h2><br>
            <h1> percentage = {{percent}} %</h1>
        </div>
        </div>
    </div>   
{% endblock %}